services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Fixpunkt\FpNewsletter\:
    resource: '../Classes/*'

  Fixpunkt\FpNewsletter\Command\ImportFEUsersScheduler:
    tags:
      - name: "console.command"
        command: "fp_newsletter:importfeusers"
        description: "Import newsletter-subscriber from tt_address for Luxletter"